blog_url: https://rpc.cnblogs.com/metaweblog/ln-xxx
blog_id: "ln-xxx"
username: "****"
password: "*****"

# 是否生成图片替换后本地文件,默认False关闭
gen_network_file: False

# 上传后是否发布，默认未发布，设置True为发布
publish: False

# 图片自定义显示格式，默认不设置
# 如设置width和居中，<center><img src="{}" style="width:100%" /></center>
img_format: ""